-- KLEID.IN realistic demo content
-- Use for local/staging testing only.
-- Run AFTER supabase/schema.sql.
-- Safe to run again: products and hero slides are upserted.

insert into public.products
(
  sku, name, slug, category, price, compare_at_price,
  wholesale_enabled, wholesale_price, wholesale_min_order, wholesale_slug,
  description, sizes, colors, color_variants, stock, featured, status,
  image_url, sort_order
)
values
(
  'KLD-TS-101',
  'Core Heavy Tee — Washed Black',
  'core-heavy-tee-washed-black',
  'T-Shirts',
  1490,
  1790,
  true,
  990,
  12,
  'core-heavy-tee-washed-black-dealer',
  '240 GSM cotton tee with a relaxed shoulder, clean neckline and washed black finish. Built for repeat everyday wear.',
  array['S','M','L','XL'],
  array['Washed Black','White','Cobalt'],
  '[
    {"name":"Washed Black","value":"#171717","stock":8,"images":["https://images.unsplash.com/photo-1583743814966-8936f37f0b?auto=format&fit=crop&w=1400&q=90"]},
    {"name":"White","value":"#f4f4f0","stock":6,"images":["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1400&q=90"]},
    {"name":"Cobalt","value":"#3156a4","stock":4,"images":["https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1400&q=90"]}
  ]'::jsonb,
  18,
  true,
  'active',
  'https://images.unsplash.com/photo-1583743814966-8936f37f0b?auto=format&fit=crop&w=1400&q=90',
  10
),
(
  'KLD-TS-102',
  'Box Fit Tee — Bone',
  'box-fit-tee-bone',
  'T-Shirts',
  1390,
  null,
  true,
  920,
  12,
  'box-fit-tee-bone-dealer',
  'Soft heavyweight cotton with a slightly cropped box fit and minimal finish.',
  array['S','M','L','XL'],
  array['Bone'],
  '[{"name":"Bone","value":"#ddd8ce","stock":22,"images":["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1400&q=90"]}]'::jsonb,
  22,
  true,
  'active',
  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1400&q=90',
  20
),
(
  'KLD-TS-103',
  'Daily Tee — Cobalt',
  'daily-tee-cobalt',
  'T-Shirts',
  1290,
  1490,
  false,
  null,
  null,
  null,
  'Everyday cotton jersey tee in KLEID.IN cobalt with a straight relaxed fit.',
  array['S','M','L','XL'],
  array['Cobalt Blue'],
  '[{"name":"Cobalt Blue","value":"#3156a4","stock":4,"images":["https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1400&q=90"]}]'::jsonb,
  4,
  true,
  'active',
  'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1400&q=90',
  30
),
(
  'KLD-SH-201',
  'Relaxed Oxford Shirt — White',
  'relaxed-oxford-shirt-white',
  'Shirts',
  2290,
  2590,
  true,
  1590,
  8,
  'relaxed-oxford-shirt-white-dealer',
  'A clean oxford shirt with a relaxed body, soft collar and easy everyday structure.',
  array['S','M','L','XL'],
  array['White'],
  '[{"name":"White","value":"#f4f4f0","stock":13,"images":["https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1400&q=90"]}]'::jsonb,
  13,
  true,
  'active',
  'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1400&q=90',
  40
),
(
  'KLD-SH-202',
  'Resort Shirt — Slate',
  'resort-shirt-slate',
  'Shirts',
  2190,
  null,
  false,
  null,
  null,
  null,
  'Lightweight open-collar shirt designed for warm days and clean layered styling.',
  array['S','M','L','XL'],
  array['Slate'],
  '[{"name":"Slate","value":"#59636f","stock":7,"images":["https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?auto=format&fit=crop&w=1400&q=90"]}]'::jsonb,
  7,
  false,
  'active',
  'https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?auto=format&fit=crop&w=1400&q=90',
  50
),
(
  'KLD-OS-301',
  'Utility Overshirt — Midnight',
  'utility-overshirt-midnight',
  'Overshirts',
  2990,
  3390,
  true,
  2090,
  6,
  'utility-overshirt-midnight-dealer',
  'Midweight overshirt with utility pockets, matte hardware and a straight relaxed fit.',
  array['M','L','XL'],
  array['Midnight Navy'],
  '[{"name":"Midnight Navy","value":"#182238","stock":3,"images":["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1400&q=90"]}]'::jsonb,
  3,
  true,
  'active',
  'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1400&q=90',
  60
),
(
  'KLD-BT-501',
  'Relaxed Trouser — Black',
  'relaxed-trouser-black',
  'Bottoms',
  2590,
  null,
  false,
  null,
  null,
  null,
  'Straight relaxed trouser with a clean front, soft drape and everyday comfort.',
  array['28','30','32','34','36'],
  array['Black'],
  '[{"name":"Black","value":"#111111","stock":15,"images":["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1400&q=90"]}]'::jsonb,
  15,
  true,
  'active',
  'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1400&q=90',
  70
),
(
  'KLD-AC-601',
  'Logo Cap — Black',
  'logo-cap-black',
  'Accessories',
  990,
  null,
  false,
  null,
  null,
  null,
  'Six-panel cotton cap with subtle KLEID.IN branding and an adjustable back strap.',
  array['One Size'],
  array['Black'],
  '[{"name":"Black","value":"#111111","stock":0,"images":["https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=1400&q=90"]}]'::jsonb,
  0,
  false,
  'sold-out',
  'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=1400&q=90',
  80
)
on conflict (sku) do update set
  name = excluded.name,
  slug = excluded.slug,
  category = excluded.category,
  price = excluded.price,
  compare_at_price = excluded.compare_at_price,
  wholesale_enabled = excluded.wholesale_enabled,
  wholesale_price = excluded.wholesale_price,
  wholesale_min_order = excluded.wholesale_min_order,
  wholesale_slug = excluded.wholesale_slug,
  description = excluded.description,
  sizes = excluded.sizes,
  colors = excluded.colors,
  color_variants = excluded.color_variants,
  stock = excluded.stock,
  featured = excluded.featured,
  status = excluded.status,
  image_url = excluded.image_url,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.hero_slides
(
  id, kind, product_id, label, title, subtitle, button_text, cta_href,
  badge, discount_text, image_url, starts_at, ends_at, show_countdown,
  cta_style, image_position, enabled, sort_order
)
values
(
  '11111111-1111-4111-8111-111111111111',
  'product',
  (select id from public.products where sku = 'KLD-TS-101'),
  'FEATURED PRODUCT',
  'CORE HEAVY TEE',
  'Washed black. Heavy cotton. Built for everyday rotation.',
  'View product',
  '/products/core-heavy-tee-washed-black',
  'NEW DROP',
  '',
  '',
  null,
  null,
  false,
  'light',
  'center',
  true,
  10
),
(
  '22222222-2222-4222-8222-222222222222',
  'offer',
  (select id from public.products where sku = 'KLD-SH-201'),
  '72 HOUR OFFER',
  'OXFORD WEEKEND',
  'A short promotional window on the relaxed white oxford.',
  'Shop offer',
  '/products/relaxed-oxford-shirt-white',
  'LIMITED TIME',
  '15% OFF',
  '',
  now() - interval '1 hour',
  now() + interval '71 hours',
  true,
  'light',
  'center',
  true,
  20
),
(
  '33333333-3333-4333-8333-333333333333',
  'collection',
  null,
  'COLLECTION',
  'THE EVERYDAY EDIT',
  'T-shirts, shirts and trousers made for repeat wear.',
  'Shop collection',
  '/products',
  'KLEID.IN',
  '',
  'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1800&q=92',
  null,
  null,
  false,
  'outline',
  'center',
  true,
  30
),
(
  '44444444-4444-4444-8444-444444444444',
  'custom',
  null,
  'COMING NEXT',
  'NEW COLOURS SOON',
  'A custom campaign example kept disabled until you decide to publish it.',
  'Explore',
  '/products',
  'DRAFT CAMPAIGN',
  '',
  'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1800&q=92',
  null,
  null,
  false,
  'dark',
  'right',
  false,
  40
)
on conflict (id) do update set
  kind = excluded.kind,
  product_id = excluded.product_id,
  label = excluded.label,
  title = excluded.title,
  subtitle = excluded.subtitle,
  button_text = excluded.button_text,
  cta_href = excluded.cta_href,
  badge = excluded.badge,
  discount_text = excluded.discount_text,
  image_url = excluded.image_url,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  show_countdown = excluded.show_countdown,
  cta_style = excluded.cta_style,
  image_position = excluded.image_position,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.offers
(
  id, title, badge, discount_text, description, cta_label, cta_href,
  image_url, starts_at, ends_at, enabled, priority
)
values
(
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'Weekend Edit',
  'WEEKEND OFFER',
  '20%',
  'Selected everyday essentials at a limited-time price.',
  'Shop the Edit',
  '/products',
  'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1800&q=92',
  now(),
  now() + interval '72 hours',
  true,
  100
)
on conflict (id) do update set
  title = excluded.title,
  badge = excluded.badge,
  discount_text = excluded.discount_text,
  description = excluded.description,
  cta_label = excluded.cta_label,
  cta_href = excluded.cta_href,
  image_url = excluded.image_url,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  enabled = excluded.enabled,
  priority = excluded.priority,
  updated_at = now();

update public.site_settings
set
  whatsapp_number = '919876543210',
  announcement_text = 'Free shipping on prepaid orders above ₹1,999',
  announcement_link_label = 'Shop the collection',
  instagram_url = '',
  support_email = 'hello@kleid.in',
  updated_at = now()
where id = 1;
