export type AboutPrinciple = {
  title: string;
  copy: string;
};

export type StoreSettings = {
  whatsappNumber: string;
  instagramUrl: string;
  facebookUrl: string;
  supportEmail: string;
  footerTagline: string;
  homeProductHeroEnabled: boolean;
  homeProductSelectorEnabled: boolean;
  demoProductsEnabled: boolean;
  homeCustomOffersEnabled: boolean;
  homeFeaturedEnabled: boolean;
  homeAboutEnabled: boolean;
  homeCatalogEnabled: boolean;
  homeDealersEnabled: boolean;
  homeSpotlightEnabled: boolean;
  homeAnimationBarsEnabled: boolean;
  footerEnabled: boolean;

  announcementEnabled: boolean;
  announcementText: string;
  announcementButtonLabel: string;
  announcementButtonHref: string;
  homeDefaultHeroEnabled: boolean;
  homeDefaultHeroLabel: string;
  homeDefaultHeroBrand: string;
  homeDefaultHeroTitle: string;
  homeDefaultHeroSubtitle: string;
  homeDefaultHeroButtonLabel: string;
  homeDefaultHeroButtonHref: string;
  homeDefaultHeroImageUrl: string;
  homeDefaultHeroImagePosition: "left" | "center" | "right";
  homeCatalogEyebrow: string;
  homeCatalogTitle: string;
  homeBrandEyebrow: string;
  homeBrandTitle: string;
  homeAboutButtonLabel: string;
  homeDealersEyebrow: string;
  homeDealersTitle: string;
  homeDealersBody: string;
  homeDealersButtonLabel: string;
  homeDealerTags: string[];
  homeSpotlightBadge: string;
  homeShowcaseProductUrls: string[];
  aboutHeroEyebrow: string;
  aboutHeroTitle: string;
  aboutHeroLead: string;
  aboutHeroBody: string;
  aboutMissionEyebrow: string;
  aboutMissionTitle: string;
  aboutMissionBody: string;
  aboutPhilosophyEyebrow: string;
  aboutPhilosophyTitle: string;
  aboutPhilosophyBody: string;
  aboutPrinciples: AboutPrinciple[];
  aboutBuiltEyebrow: string;
  aboutBuiltTitle: string;
  aboutBuiltBody: string;
  aboutFutureEyebrow: string;
  aboutFutureTitle: string;
  aboutFutureBody: string;
  aboutShopButtonLabel: string;
  aboutWhatsappButtonLabel: string;
};

